# Generated by Django 4.0.4 on 2022-05-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionales',
            name='edad',
        ),
        migrations.AddField(
            model_name='profesionales',
            name='cargo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
