# Generated by Django 4.0.4 on 2022-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0002_remove_profesionales_edad_profesionales_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.AlterModelOptions(
            name='profesionales',
            options={'verbose_name_plural': 'Profesionales'},
        ),
    ]
