# Generated by Django 4.0.4 on 2022-05-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0003_consultas_alter_profesionales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='consulta',
            field=models.TextField(default=''),
        ),
    ]
