# Generated by Django 4.0.4 on 2022-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0004_consultas_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destino',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='destino',
            name='pais',
            field=models.CharField(default='', max_length=40),
        ),
    ]
