# Generated by Django 4.0.4 on 2022-05-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0005_remove_destino_ubicacion_destino_pais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Cliente',
        ),
    ]
